# Example .env.toml configuration file
# This replaces .env.sample with a cleaner, more structured format

[metadata]
project_name = "speech-to-copilot"
env_tag = "dev"
label_prefix = "volkb79.vxxu.de"

[control]
compose_start_mode = "abort-on-failure"
reset_before_start = "none"
image_check_enabled = false
image_check_continue_on_error = false

[infrastructure]
public_fqdn = "ra-r2001.vxxu.de"
public_tls_key_pem = "/etc/letsencrypt/live/${PUBLIC_FQDN}/privkey.pem"
public_tls_crt_pem = "/etc/letsencrypt/live/${PUBLIC_FQDN}/fullchain.pem"

[health]
interval = "10s"
timeout = "5s"
retries = 3
start_period = "30s"

[user]
uid = "$(id -u)"
gid = "$(id -g)"

[registry]
url = "https://RA-R2001.vxxu.de:5000/"

[dependencies]
paths = ["../whisper-trans", "../oobabooga-llm"]

[hooks]
pre_compose = [
    {script = "pre_setup.py", description = "Initialize system", env_exports = ["SYSTEM_TOKEN"]},
]
post_compose = [
    "post_setup.py"
]

[variables]
# Simple string values
DEMO_MODE = "false"
LOG_LEVEL = "info"

# Complex configurations with metadata
API_TOKEN = {type = "token", length = 64, charset = "hex", source = "internal", description = "API authentication token"}
DATABASE_PASSWORD = {type = "password", length = 32, charset = "alnum", source = "internal", required = true}
EXTERNAL_API_KEY = {type = "token", source = "external", description = "Third-party service API key"}

# Deferred generation (set by hooks)
ADMIN_TOKEN = {type = "token", length = 40, deferred = true, hook = "create_admin", description = "Generated after admin user creation"}

# Path variables with validation
CONFIG_PATH = {type = "path", value = "./config", validation_regex = "^\\.?/?[\\w/.-]+$"}

# Boolean and number types
ENABLE_FEATURE_X = {type = "boolean", value = "true"}
MAX_CONNECTIONS = {type = "number", value = "100", validation_regex = "^[1-9]\\d*$"}

# Quoted strings that need preservation
MODEL_NOTES = {type = "string", value = "Set MODEL_CONVERSION=stub to see guidance if HF_FILE isn't .gguf"}

# Host directory mappings
[variables.host_directories]
WEBAPP_HOSTDIR_LOGS = "./vol-webapp-logs"
API_HOSTDIR_LOGS = "./vol-api-logs"
REDIS_HOSTDIR_DATA = "./vol-redis-data"

# Service-specific configuration
[services.webapp]
port = 3000
log_level = "info"

[services.api]
port = 8000
cors_origins = "https://${PUBLIC_FQDN}"
rate_limit_rpm = 60
max_audio_duration = 300

[services.external]
whisper_url = "https://${PUBLIC_FQDN}:9443"
llm_url = "https://${PUBLIC_FQDN}:8443"