#!/usr/bin/env python3
"""
Workspace environment loader for DST-DNS.

This module reads .env.workspace files generated by env-workspace-setup-generate.sh
and exposes the values as process environment variables.
"""

from __future__ import annotations

import os
import shlex
from pathlib import Path
from typing import Dict, Iterable


class WorkspaceEnvError(ValueError):
    """Raised when workspace environment file is missing or invalid."""


def find_workspace_env(start_dir: Path) -> Path:
    """Find .env.workspace by walking up from start_dir.

    Priority:
    1. REPO_ROOT environment variable (if set)
    2. Walk up directory tree from start_dir
    """
    repo_root = os.environ.get("REPO_ROOT")
    if repo_root:
        candidate = Path(repo_root).resolve() / ".env.workspace"
        if candidate.exists():
            return candidate

    current = start_dir.resolve()
    while True:
        candidate = current / ".env.workspace"
        if candidate.exists():
            return candidate
        if current == current.parent:
            break
        current = current.parent

    raise WorkspaceEnvError(
        "Workspace environment file .env.workspace not found. "
        "Run env-workspace-setup-generate.sh to generate it."
    )


def parse_workspace_env(path: Path) -> Dict[str, str]:
    """Parse .env.workspace into a dict of key/value pairs."""
    values: Dict[str, str] = {}

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :].strip()

        lexer = shlex.shlex(line, posix=True)
        lexer.whitespace_split = True
        lexer.commenters = "#"
        tokens = list(lexer)
        if not tokens:
            continue
        if len(tokens) != 1 or "=" not in tokens[0]:
            raise WorkspaceEnvError(
                f"Invalid .env.workspace entry: {raw_line!r}"
            )

        key, value = tokens[0].split("=", 1)
        key = key.strip()
        if not key:
            raise WorkspaceEnvError(
                f"Invalid .env.workspace entry (empty key): {raw_line!r}"
            )
        values[key] = value

    return values


def load_workspace_env(start_dir: Path, override: bool = False) -> Dict[str, str]:
    """Load .env.workspace and populate os.environ.

    Args:
        start_dir: Directory to begin searching for .env.workspace
        override: If True, overwrite existing os.environ values

    Returns:
        Dict of loaded values (from file)
    """
    env_path = find_workspace_env(start_dir)
    values = parse_workspace_env(env_path)

    for key, value in values.items():
        if override or key not in os.environ:
            os.environ[key] = value

    return values


def ensure_workspace_env(required_keys: Iterable[str]) -> None:
    """Ensure required environment variables are present.

    Raises WorkspaceEnvError if any are missing or empty.
    """
    missing = [key for key in required_keys if not os.environ.get(key)]
    if missing:
        missing_str = ", ".join(missing)
        raise WorkspaceEnvError(
            "Missing required workspace environment variables: "
            f"{missing_str}. "
            "Run env-workspace-setup-generate.sh and source .env.workspace."
        )
